#!/bin/bash

# 确保以root身份运行
if [ "$EUID" -ne 0 ]; then 
    echo "请以root身份运行此脚本"
    exit 1
fi

# 设置陷阱以清理临时文件
trap 'cleanup' EXIT SIGINT SIGTERM

cleanup() {
    if [ -d "$TMP_DIR" ]; then
        rm -rf "$TMP_DIR"
        echo "已清理临时目录 $TMP_DIR"
    fi
}

# 定义变量
XRAYR_INSTALL_SCRIPT="https://raw.githubusercontent.com/XrayR-project/XrayR-release/master/install.sh"
CONFIG_REPO="https://github.com/latonyahigr/warpusa.git"
CONFIG_DIR="/etc/XrayR"
TMP_DIR="/tmp/xrayr-config"

# 日志记录
exec > >(tee -i /var/log/xrayr-install.log)
exec 2>&1

# Step 1: 安装 XrayR
echo "正在安装 XrayR..."
install_xrayr || { echo "XrayR 安装失败"; exit 1; }

install_xrayr() {
    bash <(curl -Ls $XRAYR_INSTALL_SCRIPT) && echo "XrayR 安装完成"
}

# Step 2: 克隆配置文件仓库
echo "下载配置文件..."
rm -rf "$TMP_DIR" && git clone "$CONFIG_REPO" "$TMP_DIR" || { echo "克隆配置文件库失败"; exit 1; }

# Step 3: 检查并替换配置文件
echo "检查并替换配置文件..."
mkdir -p "$CONFIG_DIR" && chmod 755 "$CONFIG_DIR" || { echo "创建或设置权限于 $CONFIG_DIR 失败"; exit 1; }

move_config_file() {
    local src=$1
    local dest=$2
    if [ -f "$src" ]; then
        mv "$src" "$dest" && echo "已替换 $(basename $dest) 文件"
    else
        echo "$(basename $src) 文件不存在，请检查"
    fi
}

move_config_file "$TMP_DIR/custom_outbound.json" "$CONFIG_DIR/custom_outbound.json"
move_config_file "$TMP_DIR/route.json" "$CONFIG_DIR/route.json"

# Step 4: 写入主配置文件
echo "写入 config.yml 配置..."
cat <<EOF > "$CONFIG_DIR/config.yml"
Log:
  Level: none
  AccessPath: # /etc/XrayR/access.log
  ErrorPath: # /etc/XrayR/error.log
DnsConfigPath: # /etc/XrayR/dns.json # Path to dns config, check https://xtls.github.io/config/dns.html for help
RouteConfigPath: $CONFIG_DIR/route.json # Path to route config, check https://xtls.github.io/config/routing.html for help
InboundConfigPath: # /etc/XrayR/custom_inbound.json # Path to custom inbound config, check https://xtls.github.io/config/inbound.html for help
OutboundConfigPath: $CONFIG_DIR/custom_outbound.json # Path to custom outbound config, check https://xtls.github.io/config/outbound.html for help
ConnectionConfig:
  Handshake: 4 # Handshake time limit, Second
  ConnIdle: 30 # Connection idle time limit, Second
  UplinkOnly: 2 # Time limit when the connection downstream is closed, Second
  DownlinkOnly: 4 # Time limit when the connection is closed after the uplink is closed, Second
  BufferSize: 64 # The internal cache size of each connection, kB
Nodes:
  - PanelType: "V2board"
    ApiConfig:
      ApiHost: "${API_HOST_1:-https://example.com}"
      ApiKey: "${API_KEY_1:-your_api_key_here}"
      NodeID: ${NODE_ID_1:-1}
      NodeType: V2ray
    ControllerConfig:
      CertConfig:
        CertMode: none
  # ... 更多节点可以按照上述格式添加 ...
EOF

# Step 5: 重启 XrayR 服务
echo "重启 XrayR 服务..."
systemctl restart XrayR && echo "XrayR 服务重启成功" || { echo "重启 XrayR 服务失败"; exit 1; }

# Step 6: 安装 BBR
echo "安装 BBR..."
install_bbr || { echo "BBR 安装失败"; exit 1; }

install_bbr() {
    bash <(curl -Ls "https://neko.nnr.moe/ii.sh") && echo "BBR 安装完成"
}

echo "所有操作完成！"
